### PR TITLE
Broadcast transactions signed with Ledger

### LINKED ISSUE #424: Broadcast transactions signed with Ledger to local blockchain
To make sure everything works, we want to broadcast the signed transactions to the local development wasmd

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #424

Note: tests run fine individually. However, running both signing tests consecutively fails for me. I don't think this is a big problem since those tests need to be executed manually anyways. Let's look into https://github.com/CosmWasm/cosmjs/issues/441 before fine tuning USB connectivity problems.

### CODE REVIEW

**Comment by willclarktech** [comment]
Re the second test hanging, it might be related to this? https://github.com/CosmWasm/cosmjs/blob/master/packages/launchpad-ledger/demo/node.js#L15-L16

I tried adding a passphrase to my device but I couldn't get the accounts test to work (addresses and pubkeys just different). What do I need to do exactly?

**Comment by webmaster128** [comment]
> I tried adding a passphrase to my device but I couldn't get the accounts test to work (addresses and pubkeys just different). What do I need to do exactly?

Did you reset your Ledger using [this 12 word mnemonic](https://github.com/CosmWasm/cosmjs/commit/b46ab541beb8b5867f9943c2f239d632496ae04f)? No passphrase should be used.

**Comment by webmaster128** [comment]
> Re the second test hanging, it might be related to this? https://github.com/CosmWasm/cosmjs/blob/master/packages/launchpad-ledger/demo/node.js#L15-L16

That [helped](https://github.com/CosmWasm/cosmjs/pull/438/commits/fdfed1bb16205bfab717b9f2ddfdfddcef8d5741) indeed, nice.

I also added a section to the README that should include all steps required to run the tests.

**Comment by willclarktech** [comment]
> Did you reset your Ledger using [this 12 word mnemonic](https://github.com/CosmWasm/cosmjs/commit/b46ab541beb8b5867f9943c2f239d632496ae04f)? No passphrase should be used.

I... added a "temporary passphrase". Is this what I need? https://support.ledger.com/hc/en-us/articles/360005434914

**Comment by webmaster128** [comment]
> Is this what I need instead? https://support.ledger.com/hc/en-us/articles/360005434914

Yes. Everything on a Ledger is derives from a single mnemonic (or "recovery phrase"). The passphases can be used to derive different wallets from this mnemonic [as specified here](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#From_mnemonic_to_seed):

> To create a binary seed from the mnemonic, we use the PBKDF2 function with a mnemonic sentence (in UTF-8 NFKD) used as the password and the string "mnemonic" + passphrase (again in UTF-8 NFKD) used as the salt.

**Review by willclarktech — APPROVED** [review]
It works! One question: do we really need to distinguish between `LEDGER_ENABLED` and `LEDGER_INTERACTIVE_ENABLED`?

Also can we link to this article from the README? https://support.ledger.com/hc/en-us/articles/360005434914

**Comment by webmaster128** [comment]
Nice!

> do we really need to distinguish between `LEDGER_ENABLED` and `LEDGER_INTERACTIVE_ENABLED`?

No we don't. It is handy when your regularly test code that does not require user interaction (such as get address, get app version, …). For what we do here it can be considered overengineering. Should I merge them?

> Also can we link to this article from the README? https://support.ledger.com/hc/en-us/articles/360005434914

Yes, makes sense

**Comment by willclarktech** [comment]
> Should I merge them?

I think we should, at least until our CI provider can give us a Ledger device plugged into the server with a passphrase of our choice.

**Comment by webmaster128** [comment]
Okay, then we have two more commits starting with _Add link how to initialize a Ledger 873f8c0_. Then this should be done.

**Review by willclarktech — APPROVED** [review]

**Pull request merged**
